/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DataStorage__factory } from "./DataStorage__factory";
export { RedPacket__factory } from "./RedPacket__factory";
