/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface DataStorageInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "allData"
      | "directTransfer"
      | "getAllDataCount"
      | "getBalance"
      | "getDataByIndex"
      | "getUserDataCount"
      | "userDataMap"
      | "writeData"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "DataWritten" | "DirectTransfer"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "allData",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "directTransfer",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAllDataCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDataByIndex",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserDataCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userDataMap",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "writeData", values: [string]): string;

  decodeFunctionResult(functionFragment: "allData", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "directTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllDataCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBalance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getDataByIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserDataCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userDataMap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "writeData", data: BytesLike): Result;
}

export namespace DataWrittenEvent {
  export type InputTuple = [
    sender: AddressLike,
    content: string,
    value: BigNumberish,
    timestamp: BigNumberish,
    dataId: BigNumberish
  ];
  export type OutputTuple = [
    sender: string,
    content: string,
    value: bigint,
    timestamp: bigint,
    dataId: bigint
  ];
  export interface OutputObject {
    sender: string;
    content: string;
    value: bigint;
    timestamp: bigint;
    dataId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DirectTransferEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    from: string,
    to: string,
    amount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    from: string;
    to: string;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DataStorage extends BaseContract {
  connect(runner?: ContractRunner | null): DataStorage;
  waitForDeployment(): Promise<this>;

  interface: DataStorageInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  allData: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint] & {
        sender: string;
        content: string;
        timestamp: bigint;
        value: bigint;
      }
    ],
    "view"
  >;

  directTransfer: TypedContractMethod<[], [void], "payable">;

  getAllDataCount: TypedContractMethod<[], [bigint], "view">;

  getBalance: TypedContractMethod<[], [bigint], "view">;

  getDataByIndex: TypedContractMethod<
    [_index: BigNumberish],
    [
      [string, string, bigint, bigint] & {
        sender: string;
        content: string;
        timestamp: bigint;
        value: bigint;
      }
    ],
    "view"
  >;

  getUserDataCount: TypedContractMethod<[_user: AddressLike], [bigint], "view">;

  userDataMap: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [string, string, bigint, bigint] & {
        sender: string;
        content: string;
        timestamp: bigint;
        value: bigint;
      }
    ],
    "view"
  >;

  writeData: TypedContractMethod<[_content: string], [void], "payable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "allData"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint] & {
        sender: string;
        content: string;
        timestamp: bigint;
        value: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "directTransfer"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "getAllDataCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getDataByIndex"
  ): TypedContractMethod<
    [_index: BigNumberish],
    [
      [string, string, bigint, bigint] & {
        sender: string;
        content: string;
        timestamp: bigint;
        value: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserDataCount"
  ): TypedContractMethod<[_user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "userDataMap"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [string, string, bigint, bigint] & {
        sender: string;
        content: string;
        timestamp: bigint;
        value: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "writeData"
  ): TypedContractMethod<[_content: string], [void], "payable">;

  getEvent(
    key: "DataWritten"
  ): TypedContractEvent<
    DataWrittenEvent.InputTuple,
    DataWrittenEvent.OutputTuple,
    DataWrittenEvent.OutputObject
  >;
  getEvent(
    key: "DirectTransfer"
  ): TypedContractEvent<
    DirectTransferEvent.InputTuple,
    DirectTransferEvent.OutputTuple,
    DirectTransferEvent.OutputObject
  >;

  filters: {
    "DataWritten(address,string,uint256,uint256,uint256)": TypedContractEvent<
      DataWrittenEvent.InputTuple,
      DataWrittenEvent.OutputTuple,
      DataWrittenEvent.OutputObject
    >;
    DataWritten: TypedContractEvent<
      DataWrittenEvent.InputTuple,
      DataWrittenEvent.OutputTuple,
      DataWrittenEvent.OutputObject
    >;

    "DirectTransfer(address,address,uint256,uint256)": TypedContractEvent<
      DirectTransferEvent.InputTuple,
      DirectTransferEvent.OutputTuple,
      DirectTransferEvent.OutputObject
    >;
    DirectTransfer: TypedContractEvent<
      DirectTransferEvent.InputTuple,
      DirectTransferEvent.OutputTuple,
      DirectTransferEvent.OutputObject
    >;
  };
}
