/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface RedPacketInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "claimPacket"
      | "createPacket"
      | "creatorPackets"
      | "getCreatorPackets"
      | "getPacketInfo"
      | "getTotalPackets"
      | "getUserClaimedPackets"
      | "hasClaimed"
      | "packetIdCounter"
      | "packets"
      | "userClaimedPackets"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AlreadyClaimed"
      | "PacketClaimed"
      | "PacketCreated"
      | "PacketFinished"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "claimPacket",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createPacket",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "creatorPackets",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCreatorPackets",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPacketInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalPackets",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserClaimedPackets",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasClaimed",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "packetIdCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "packets",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userClaimedPackets",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "claimPacket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createPacket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "creatorPackets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCreatorPackets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPacketInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalPackets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserClaimedPackets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasClaimed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "packetIdCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "packets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "userClaimedPackets",
    data: BytesLike
  ): Result;
}

export namespace AlreadyClaimedEvent {
  export type InputTuple = [
    packetId: BigNumberish,
    claimer: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    packetId: bigint,
    claimer: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    packetId: bigint;
    claimer: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PacketClaimedEvent {
  export type InputTuple = [
    packetId: BigNumberish,
    claimer: AddressLike,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    packetId: bigint,
    claimer: string,
    amount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    packetId: bigint;
    claimer: string;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PacketCreatedEvent {
  export type InputTuple = [
    packetId: BigNumberish,
    creator: AddressLike,
    totalAmount: BigNumberish,
    count: BigNumberish,
    isRandom: boolean,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    packetId: bigint,
    creator: string,
    totalAmount: bigint,
    count: bigint,
    isRandom: boolean,
    timestamp: bigint
  ];
  export interface OutputObject {
    packetId: bigint;
    creator: string;
    totalAmount: bigint;
    count: bigint;
    isRandom: boolean;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PacketFinishedEvent {
  export type InputTuple = [packetId: BigNumberish, timestamp: BigNumberish];
  export type OutputTuple = [packetId: bigint, timestamp: bigint];
  export interface OutputObject {
    packetId: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RedPacket extends BaseContract {
  connect(runner?: ContractRunner | null): RedPacket;
  waitForDeployment(): Promise<this>;

  interface: RedPacketInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  claimPacket: TypedContractMethod<
    [_packetId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createPacket: TypedContractMethod<
    [_count: BigNumberish, _isRandom: boolean],
    [void],
    "payable"
  >;

  creatorPackets: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getCreatorPackets: TypedContractMethod<
    [_creator: AddressLike],
    [bigint[]],
    "view"
  >;

  getPacketInfo: TypedContractMethod<
    [_packetId: BigNumberish],
    [
      [string, bigint, bigint, bigint, bigint, bigint, boolean] & {
        creator: string;
        totalAmount: bigint;
        remainingAmount: bigint;
        totalCount: bigint;
        remainingCount: bigint;
        createdAt: bigint;
        isRandom: boolean;
      }
    ],
    "view"
  >;

  getTotalPackets: TypedContractMethod<[], [bigint], "view">;

  getUserClaimedPackets: TypedContractMethod<
    [_user: AddressLike],
    [bigint[]],
    "view"
  >;

  hasClaimed: TypedContractMethod<
    [_packetId: BigNumberish, _user: AddressLike],
    [boolean],
    "view"
  >;

  packetIdCounter: TypedContractMethod<[], [bigint], "view">;

  packets: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint, bigint, bigint, bigint, boolean] & {
        id: bigint;
        creator: string;
        totalAmount: bigint;
        remainingAmount: bigint;
        totalCount: bigint;
        remainingCount: bigint;
        createdAt: bigint;
        isRandom: boolean;
      }
    ],
    "view"
  >;

  userClaimedPackets: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "claimPacket"
  ): TypedContractMethod<[_packetId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createPacket"
  ): TypedContractMethod<
    [_count: BigNumberish, _isRandom: boolean],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "creatorPackets"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCreatorPackets"
  ): TypedContractMethod<[_creator: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getPacketInfo"
  ): TypedContractMethod<
    [_packetId: BigNumberish],
    [
      [string, bigint, bigint, bigint, bigint, bigint, boolean] & {
        creator: string;
        totalAmount: bigint;
        remainingAmount: bigint;
        totalCount: bigint;
        remainingCount: bigint;
        createdAt: bigint;
        isRandom: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTotalPackets"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserClaimedPackets"
  ): TypedContractMethod<[_user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "hasClaimed"
  ): TypedContractMethod<
    [_packetId: BigNumberish, _user: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "packetIdCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "packets"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint, bigint, bigint, bigint, boolean] & {
        id: bigint;
        creator: string;
        totalAmount: bigint;
        remainingAmount: bigint;
        totalCount: bigint;
        remainingCount: bigint;
        createdAt: bigint;
        isRandom: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "userClaimedPackets"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getEvent(
    key: "AlreadyClaimed"
  ): TypedContractEvent<
    AlreadyClaimedEvent.InputTuple,
    AlreadyClaimedEvent.OutputTuple,
    AlreadyClaimedEvent.OutputObject
  >;
  getEvent(
    key: "PacketClaimed"
  ): TypedContractEvent<
    PacketClaimedEvent.InputTuple,
    PacketClaimedEvent.OutputTuple,
    PacketClaimedEvent.OutputObject
  >;
  getEvent(
    key: "PacketCreated"
  ): TypedContractEvent<
    PacketCreatedEvent.InputTuple,
    PacketCreatedEvent.OutputTuple,
    PacketCreatedEvent.OutputObject
  >;
  getEvent(
    key: "PacketFinished"
  ): TypedContractEvent<
    PacketFinishedEvent.InputTuple,
    PacketFinishedEvent.OutputTuple,
    PacketFinishedEvent.OutputObject
  >;

  filters: {
    "AlreadyClaimed(uint256,address,uint256)": TypedContractEvent<
      AlreadyClaimedEvent.InputTuple,
      AlreadyClaimedEvent.OutputTuple,
      AlreadyClaimedEvent.OutputObject
    >;
    AlreadyClaimed: TypedContractEvent<
      AlreadyClaimedEvent.InputTuple,
      AlreadyClaimedEvent.OutputTuple,
      AlreadyClaimedEvent.OutputObject
    >;

    "PacketClaimed(uint256,address,uint256,uint256)": TypedContractEvent<
      PacketClaimedEvent.InputTuple,
      PacketClaimedEvent.OutputTuple,
      PacketClaimedEvent.OutputObject
    >;
    PacketClaimed: TypedContractEvent<
      PacketClaimedEvent.InputTuple,
      PacketClaimedEvent.OutputTuple,
      PacketClaimedEvent.OutputObject
    >;

    "PacketCreated(uint256,address,uint256,uint256,bool,uint256)": TypedContractEvent<
      PacketCreatedEvent.InputTuple,
      PacketCreatedEvent.OutputTuple,
      PacketCreatedEvent.OutputObject
    >;
    PacketCreated: TypedContractEvent<
      PacketCreatedEvent.InputTuple,
      PacketCreatedEvent.OutputTuple,
      PacketCreatedEvent.OutputObject
    >;

    "PacketFinished(uint256,uint256)": TypedContractEvent<
      PacketFinishedEvent.InputTuple,
      PacketFinishedEvent.OutputTuple,
      PacketFinishedEvent.OutputObject
    >;
    PacketFinished: TypedContractEvent<
      PacketFinishedEvent.InputTuple,
      PacketFinishedEvent.OutputTuple,
      PacketFinishedEvent.OutputObject
    >;
  };
}
